server:
  port: 8082

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_account_db
    username: payflow
    password: payflow123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  jwt:
    secret: payflow-secret-key-yang-panjang-minimal-256bit-untuk-hs256-algorithm